enum Gender {
  MALE
  FEMALE
}

enum Provider {
  GOOGLE
  FACEBOOK
}

scalar BigInt
scalar Date
scalar DateTime
scalar EmailAddress
scalar JWT

type User {
  id: BigInt!
  createdAt: DateTime
  updatedAt: DateTime
  email: EmailAddress
  name: String
  nickname: String
  dateOfBirth: Date
  gender: Gender
  areaCode: String
  phone: String
  picture: String
  socialProfiles: [SocialProfile]
}

type SocialProfile {
  sub: String!
  provider: Provider!
  createdAt: DateTime
  updatedAt: DateTime
  name: String
  email: EmailAddress
  picture: String
}

type Query {
  userById(id: BigInt!): User
}

type Mutation {
  signUp(
    email: EmailAddress!
    name: String!
    areaCode: String!
    phone: String!
  ): JWT

  signInByProvider(
    provider: Provider!
    sub: String!
    name: String
    email: String
    picture: String
  ): JWT

  signInByPhone(phone: String!): JWT
}
