FROM node:16-alpine

WORKDIR /api

COPY package*.json ./

RUN npm install

COPY src src
COPY prisma prisma
COPY ./tsconfig.json ./
COPY ./codegen.yml ./
COPY ./nodemon.json ./

EXPOSE 4000

CMD [ "npm", "run", "dev" ]
